### ISSUE TITLE
Configure assets path

### ISSUE THREAD

**Issue by MGaetan89** [JCAndKSolutions/android-unit-test#101]
I kept my tests in the `androidTest` folder so they are recognized in the Android view in Android Studio.
To do that, I use the following configuration, which works fine:

```gradle
apply plugin: 'android-unit-test'

androidUnitTest {
    sourceSets {
        testDebug {
            java.srcDirs = ['src/androidTest/java']
        }
    }
}
```

I also have some files in `androidTest/assets`, but it seems that I can not access them with `this.getClass().getResourceAsStream("/assets/file");`. I also tried `ShadowApplication.getInstance().getAssets().open("file");`, without success.

Is there a way to configure the path to the assets folder?

**Comment by MGaetan89** [comment]
I managed to work around this with the following configuration:

```gradle
android {
    sourceSets {
        main {
            assets.srcDirs = ['src/androidTest/assets']
        }
    }
}

```

And accessing the asset with the following code:

```java
InputStream inputStream = null;

try {
	inputStream = ShadowApplication.getInstance().getAssets().open("file");
}
catch (IOException exception) {
	exception.printStackTrace();
}

```

**Comment by SuperJugy** [comment]
Yeah, the assets folder is something only for android apps, for tests, you should be using the resources folder as in `src/test/resources`. you can also change the location like you did for the `java` folder. Keep in mind though that since they are normal jar resources you wouldn't open them with the `ShadowApplication` but like in regular java.

Right now your workaround works but you are ending up with test assests in your app and that is just making your app bigger unnecessarily. Also, if you want integration with AndroidStudio, read the readme section about that, there is a plugin for android studio you can install that will integrate your tests without having to hack like you did because now you can't run normal instrumentation tests since they would be also running the unit tests.

Take a look at the readme and see if that works.

**Comment by MGaetan89** [comment]
Thank you for your information.

I don't know how I missed the Android Studio plugin. But in the Android view, it does not recognize the `test` folder, but that's an issue I can report in their repository.

I put my tests files in `src/test/resources`, but with the following code, I get a `null` value. Any idea why?

```java
InputStream inputStream = this.getClass().getResourceAsStream("file"); // Returns null, "file" is in src/test/resources
```

**Comment by MGaetan89** [comment]
Answering to myself, it all seem to be cause by the Android Studio plugin:
evant/android-studio-unit-test-plugin#4
evant/android-studio-unit-test-plugin#12

**Comment by SuperJugy** [comment]
Yeah, if it is working in the console then it is a bug in the android studio plugin.

**Comment by MGaetan89** [comment]
It's working in the console, yes.
Thanks for your help ;-)
