### ISSUE TITLE
Test folder not marked as source directory in Android Studio 1.1 preview 2

### ISSUE THREAD

**Issue by nhaarman** [JCAndKSolutions/android-unit-test#102]
The `src/test/java` folder is not marked as source directory in the latest Android Studio canary channel version.

Project `build.gradle`:

```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.1'

        classpath 'org.robolectric:robolectric-gradle-plugin:0.14.1'
        classpath 'com.github.jcandksolutions.gradle:android-unit-test:2.1.1'
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}
```

Module `build.gradle`:

```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.example"
        minSdkVersion 21
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
}

apply plugin: 'android-unit-test'

dependencies {
    testCompile 'junit:junit:4.11'
    testCompile 'org.robolectric:robolectric:2.4'
}
```

Manually adding the folder to the test source set doesn't help either:

```groovy
androidUnitTest {
    sourceSets {
        test {
            java.srcDirs = ["src/test/java"]
        }
    }
}
```

The `src/androidTest/java` folder *is* marked as source directory however.

Also, running `./gradlew test` *does* execute the tests in `src/test/java`.

**Comment by SuperJugy** [comment]
Please read the README. This plugin is just a gradle plugin and has no way to make an integration with Android Studio UI. There is however an android studio plugin that integrates this plugin with android studio which is detailed in the README.

Also the `src/androidTest/java` folder is the standard emulator based testing that the android plugin provides nativly which does have native integration with Android Studio and has nothing to do with this plugin. If you run the `test` task it will execute the unit tests from this plugin, if you run the `check` task however it will run both this plugin's `test` task and android's plugin emulator based tests which require an emulator running. This is so that you can make unit tests in JVM and instrumentation or integration tests in the real device.

**Comment by nhaarman** [comment]
My apologies. I must have misunderstood.

**Comment by SuperJugy** [comment]
No problem at all, here is the link to the android studio plugin so you can have integration in android studio: https://github.com/evant/android-studio-unit-test-plugin
