### ISSUE TITLE
javaResources are not copied

### ISSUE THREAD

**Issue by lapastillaroja** [JCAndKSolutions/android-unit-test#97]
Flavor's `javaResources` files are not copied to the `build` folder when executing the test task.

I have some `properties` files in `/src/FLAVOR/resources` folder. There is a way to make this plugin to copy those files to the `build/intermediates` folder like the `res` folder?

**Comment by SuperJugy** [comment]
This plugin does not copy any file at all, the build/intermidiates is something that the android plugin uses. Why would you need to copy your resources anyway? they should be in the resources classpath IIRC. Have you checked the jar to see if it has resources?

**Comment by lapastillaroja** [comment]
Sorry, my english isn't good but I'll try to explain it better.

I'm using some third party libraries like the New Relic's [Android SDK](https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-installation/android/installing-android-apps-gradle-android-studio). This library requires to have a `newrelic.properties` with the application code in the project's root directory. Because I have different application code for each flavor (`dev`, `stg`) I have this folder structure.

`app/src/dev/resources/newrelic.properties`  
`app/src/stg/resources/newrelic.properties`  

Test folder is in `app/src/test` folder.

My problem is when executing `./gradlew clean testDevDebug` fails because there is no `newrelic.properties` in `app/src/test/resources` folder. I think the expected behaviour should be to look for the properties file in the `dev` folder, not in `test`

Sorry in advance if this is not related with your plugin.

**Comment by SuperJugy** [comment]
Hmm, well, Android plugin doesn't support the `resources` folder, it uses `res` folder. I don't know how that modified android sdk works but it is something I can't so much about. What I can tell you is that this plugin supports the resource dirs for tests like `src/test/resources`, `src/testDebug/resources`, `src/testDev/resources`, `src/testDevDebug/resources`, etc. I don't know if your custom sdk will pick those folders though. I don't think there is much I can do since we only support the standard android plugin.

**Comment by mttmllns** [comment]
@lapastillaroja, I'm not sure if your issue is the same as ours: we need to read things like the `org.robolectric.Config.properties` file and xml files for use in unit tests.  These aren't automatically copied from src/main/test/resources so we needed to attach a copy task before the processResources tasks.  Our current solution below.  Maybe it can be modified to do what you need.

```gradle
// Copy test resources to classpath folder due to IntelliJ restrictions
// See https://code.google.com/p/android/issues/detail?id=64887
task copyTestDebugResources(type: Copy) {
	description 'Copies Robolectric test resources to the Debug build directory'
	from 'src/test/resources'
	into 'build/test-classes/debug'
}

task copyTestReleaseResources(type: Copy) {
	description 'Copies Robolectric test resources to the Release build directory'
	from 'src/test/resources'
	into 'build/test-classes/release'
}

// The android plugin defers creation of most tasks so we need to wait to create the copy dependency
tasks.whenTaskAdded { task ->
	if (task.name.equals("processTestDebugResources")) {
		task.dependsOn copyTestDebugResources
	} else if (task.name.equals("processTestReleaseResources")) {
		task.dependsOn copyTestReleaseResources
	}
}
```

**Comment by SuperJugy** [comment]
Since this can have a workaround, I will close it as it is not standard android plugin tasks.
